[build-system]
requires = ["setuptools>=62.0.0","wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.mypy]
mypy_path = "MidiCompose"
check_untyped_defs = true